#!/bin/sh

set -e

case "$1" in
	install|upgrade)
		mkdir /tmp/bak
		mv /boot/* /tmp/bak/
	;;

	abort-upgrade)
		mv /tmp/bak/* /boot
		rmdir /tmp/bak
	;;

	*)
		echo "preinst called with unknown argument \'$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
